# Generated by Django 2.1.1 on 2018-09-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
